spring:
  application:
    name: mini-im
  profiles:
    active: '@activatedProperties@'
  banner:
    location: banner.txt
logging:
  level:
    .*: info
    org.springframework.boot.autoconfigure: error
  config: classpath:logback-custom.xml